package com.g1t11.socialmagnet.data;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import com.g1t11.socialmagnet.model.farm.Crop;
import com.g1t11.socialmagnet.model.farm.Farmer;
import com.g1t11.socialmagnet.model.farm.Plot;
import com.g1t11.socialmagnet.model.farm.StealingRecord;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class TestFarmerDAO {
    private FarmerDAO farmerDAO;

    public static final Crop papaya =     new Crop("Papaya",     20, 30,  8,  75, 100, 15);
    public static final Crop pumpkin =    new Crop("Pumpkin",    30, 60,  5,   5, 200, 20);
    public static final Crop sunflower  = new Crop("Sunflower",  40, 120, 20, 15, 20,  40);
    public static final Crop watermelon = new Crop("Watermelon", 50, 240, 1,   5, 800, 10);

    @Before
    public void initDAO() {
        Database db = new Database();
        db.establishConnection();
        farmerDAO = new FarmerDAO(db);
    }

    @Test
    public void testGetFarmer() {
        Farmer expected = new Farmer("adam", "Adam Levine", 11000, 15000, 1);

        Farmer actual = farmerDAO.getFarmer("adam");

        Assert.assertNotNull(actual);
        Assert.assertEquals(expected, actual);
    }

    @Test
    public void testGetInventoryCrops() {
        Map<String, Integer> expected = new LinkedHashMap<>(Map.of("Papaya", 1, "Watermelon", 2));
        Map<String, Integer> actual = farmerDAO.getInventoryCrops("britney");
        
        Assert.assertEquals(expected, actual);
    }

    @Test
    public void testGetPlots() {
        List<Plot> expected = new ArrayList<>(List.of(
            new Plot(papaya),
            new Plot(pumpkin),
            new Plot(watermelon),
            new Plot(),
            new Plot(),
            new Plot()
        ));

        List<Plot> actual = farmerDAO.getPlots("britney", 6);

        Assert.assertEquals(expected, actual);
    }

    public void testPlantAndClearCrops() {
        testPlantCrop();
        testClearCrop();
    }

    private void testPlantCrop() {
        List<Plot> expected = farmerDAO.getPlots("adam", 6);
        expected.set(4, new Plot(papaya));

        farmerDAO.plantCrop("adam", 5, "Papaya");

        List<Plot> actual = farmerDAO.getPlots("adam", 6);

        Assert.assertEquals(expected, actual);
    }

    private void testClearCrop() {
        int expectedWealth = farmerDAO.getFarmer("adam").getWealth() - 5;

        List<Plot> expectedPlots = farmerDAO.getPlots("adam", 6);
        expectedPlots.set(4, new Plot());

        farmerDAO.clearPlot("adam", 5);

        int actualWealth = farmerDAO.getFarmer("adam").getWealth();
        List<Plot> actualPlots = farmerDAO.getPlots("adam", 6);

        Assert.assertEquals(expectedWealth, actualWealth);
        Assert.assertEquals(expectedPlots, actualPlots);
        Assert.assertTrue(false);
    }

    @Test(expected = DatabaseException.class)
    public void testPlantOnExistingCrop() {
        // Duplicate entry
        farmerDAO.plantCrop("adam", 1, "Papaya");
    }

    @Test(expected = DatabaseException.class)
    public void testPlantWithoutInventory() {
        // Duplicate entry
        farmerDAO.plantCrop("adam", 1, "Sunflower");
    }

    @Test(expected = DatabaseException.class)
    public void testPlantCropInvalidPlot() {
        farmerDAO.plantCrop("adam", 9, "Papaya");
    }

    @Test
    public void testHarvest() {
        Farmer charlieBefore = farmerDAO.getFarmer("charlie");
        int expectedMaxPlotCount = charlieBefore.getMaxPlotCount() + 1;
        int expectedWealth = charlieBefore.getWealth() + 6250;
        List<Plot> expectedPlots = List.of(
            new Plot(),
            new Plot(pumpkin),
            new Plot(watermelon),
            new Plot(),
            new Plot(),
            new Plot(),
            new Plot()
        );

        farmerDAO.harvest("charlie");

        Farmer charlieAfter = farmerDAO.getFarmer("charlie");
        int actualMaxPlotCount = charlieAfter.getMaxPlotCount();
        int actualWealth = charlieAfter.getWealth();
        List<Plot> actualPlots = farmerDAO.getPlots("charlie", 7);

        Assert.assertEquals(expectedMaxPlotCount, actualMaxPlotCount);
        Assert.assertEquals(expectedWealth, actualWealth);
        Assert.assertEquals(expectedPlots, actualPlots);
    }

    @Test
    public void testSteal() {
        testStealFirst();
        testStealAgain();
    }

    private void testStealFirst() {
        // Stolen yield is randomly generated by database
        // In this test, stealing 1-3 Papayas and 4-20 Watermelons from elijah
        List<StealingRecord> minExpectedSteal = List.of(
            new StealingRecord(papaya, 1),
            new StealingRecord(watermelon, 4)
        );
        List<StealingRecord> maxExpectedSteal = List.of(
            new StealingRecord(papaya, 3),
            new StealingRecord(watermelon, 20)
        );
        Farmer dannyBefore = farmerDAO.getFarmer("danny");

        List<StealingRecord> actualSteal = farmerDAO.steal("danny", "elijah");

        Farmer dannyAfter = farmerDAO.getFarmer("danny");
        testStealerWealthAndXP(dannyBefore, dannyAfter, minExpectedSteal, maxExpectedSteal);

        int size = actualSteal.size();
        Assert.assertEquals(minExpectedSteal.size(), size);

        for (int i = 0; i < size; i++) {
            int actualXPGained = actualSteal.get(i).getTotalXPGained();
            int actualGoldGained = actualSteal.get(i).getTotalGoldGained();
            Assert.assertTrue(minExpectedSteal.get(i).getTotalXPGained() <= actualXPGained && actualXPGained <= maxExpectedSteal.get(i).getTotalXPGained());
            Assert.assertTrue(minExpectedSteal.get(i).getTotalGoldGained() <= actualGoldGained && actualGoldGained <= maxExpectedSteal.get(i).getTotalGoldGained());
        }
    }

    private void testStealerWealthAndXP(Farmer before, Farmer after, List<StealingRecord> minExpectedSteal, List<StealingRecord> maxExpectedSteal) {
        int minGoldGained = minExpectedSteal.stream().reduce(0,
            (Integer sum, StealingRecord next) -> sum + next.getTotalGoldGained(), 
            (Integer a, Integer b) -> a + b);
        int maxGoldGained = maxExpectedSteal.stream().reduce(0,
            (Integer sum, StealingRecord next) -> sum + next.getTotalGoldGained(), 
            (Integer a, Integer b) -> a + b);
        int minXPGained = minExpectedSteal.stream().reduce(0,
            (Integer sum, StealingRecord next) -> sum + next.getTotalXPGained(), 
            (Integer a, Integer b) -> a + b);
        int maxXPGained = maxExpectedSteal.stream().reduce(0,
            (Integer sum, StealingRecord next) -> sum + next.getTotalXPGained(), 
            (Integer a, Integer b) -> a + b);

        int minExpectedWealth = before.getWealth() + minGoldGained;
        int maxExpectedWealth = before.getWealth() + maxGoldGained;
        int minExpectedXP = before.getXP() + minXPGained;
        int maxExpectedXP = before.getXP() + maxXPGained;
        int actualWealth = after.getWealth();
        int actualXP = after.getXP();

        Assert.assertTrue(minExpectedWealth <= actualWealth && actualWealth <= maxExpectedWealth);
        Assert.assertTrue(minExpectedXP <= actualXP && actualXP <= maxExpectedXP);

    }

    private void testStealAgain() {
        // Should result in no yield stolen.
        Farmer dannyBefore = farmerDAO.getFarmer("danny");
        int expectedWealth = dannyBefore.getWealth();
        int expectedXP = dannyBefore.getXP();

        List<StealingRecord> actualSteal = farmerDAO.steal("danny", "elijah");

        Farmer dannyAfter = farmerDAO.getFarmer("danny");
        int actualWealth = dannyAfter.getWealth();
        int actualXP = dannyAfter.getXP();

        Assert.assertEquals(0, actualSteal.size());
        Assert.assertEquals(expectedWealth, actualWealth);
        Assert.assertEquals(expectedXP, actualXP);
    }

    @Test
    public void testStealAlready20Percent() {
         // Should result in no yield stolen.
        Farmer elijahBefore = farmerDAO.getFarmer("elijah");
        int expectedWealth = elijahBefore.getWealth();
        int expectedXP = elijahBefore.getXP();

        List<StealingRecord> actualSteal = farmerDAO.steal("elijah", "danny");

        Farmer elijahAfter = farmerDAO.getFarmer("elijah");
        int actualWealth = elijahAfter.getWealth();
        int actualXP = elijahAfter.getXP();

        Assert.assertEquals(0, actualSteal.size());
        Assert.assertEquals(expectedWealth, actualWealth);
        Assert.assertEquals(expectedXP, actualXP);       
    }

    @Test
    public void getGiftCountToday() {
        int expected = 5;
        int actual = farmerDAO.getGiftCountToday("charlie");
        Assert.assertEquals(expected, actual);
    }
}
